In [3]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

## Create and Read

### 1D array

In [7]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.shape

(6,)

In [11]:
arr1.dtype

dtype('int32')

In [13]:
arr1.ndim

1

In [14]:
arr1.size

6

### 2D array

In [15]:
arr2 = np.array([[1,4,5],[6,7,8]])
arr2

array([[1, 4, 5],
       [6, 7, 8]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 3)

### 3D array

In [24]:
arr3 = np.array([[[3,4,6],[7,9,0]], [[5,3,6],[4,7,8]],[[5,6,7],[6,7,8]]])
arr3

array([[[3, 4, 6],
        [7, 9, 0]],

       [[5, 3, 6],
        [4, 7, 8]],

       [[5, 6, 7],
        [6, 7, 8]]])

## Accessing the array

In [36]:
arr3[0]

array([[3, 4, 6],
       [7, 9, 0]])

In [37]:
arr3[0][0]

array([3, 4, 6])

In [38]:
arr3[0][0][0]

3

In [40]:
arr3[0:2]

array([[[3, 4, 6],
        [7, 9, 0]],

       [[5, 3, 6],
        [4, 7, 8]]])

In [41]:
arr3[1][0][0]

5

In [26]:
arr3.ndim

3

In [25]:
arr3.shape

(3, 2, 3)

#### 3 layeers, each layer has  2 rows, 3 coloumns in each layer

## Create Random array

In [28]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.11308376, 0.13184175, 0.56238344],
        [0.54619959, 0.85017786, 0.95031553]],

       [[0.44690489, 0.57132132, 0.06805441],
        [0.02467934, 0.04855098, 0.05007296]],

       [[0.17798274, 0.55716312, 0.18715774],
        [0.0348563 , 0.71968858, 0.81595968]]])

In [33]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Fill the zeoroes with any number

In [34]:
full = np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

##### update the value of a single item

In [52]:
zeroes[0,1,2]=100

In [53]:
zeroes

array([[[  0.,   0.,   0.],
        [  0.,   0., 100.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.]]])

In [35]:
ones = np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## basic Maths operations

In [44]:
a1 = np.random.rand(2,3,2)
a1

array([[[0.9157898 , 0.18636138],
        [0.95354881, 0.26138318],
        [0.01103062, 0.41003444]],

       [[0.81541317, 0.94977737],
        [0.59189684, 0.90416463],
        [0.73446958, 0.91477232]]])

In [45]:
a2 = np.random.rand(2,3,2)
a2

array([[[0.05965798, 0.32694381],
        [0.36090496, 0.7409633 ],
        [0.98322394, 0.16248604]],

       [[0.56001093, 0.42343114],
        [0.8054208 , 0.23266327],
        [0.38271634, 0.89841775]]])

In [46]:
np.add(a1,a2)

array([[[0.97544778, 0.51330519],
        [1.31445377, 1.00234648],
        [0.99425456, 0.57252047]],

       [[1.37542411, 1.3732085 ],
        [1.39731763, 1.1368279 ],
        [1.11718592, 1.81319007]]])

In [47]:
np.multiply(a1,a2)

array([[[0.05463417, 0.0609297 ],
        [0.34414049, 0.19367534],
        [0.01084557, 0.06662487]],

       [[0.45664029, 0.40216531],
        [0.47672602, 0.2103659 ],
        [0.28109351, 0.82184769]]])

In [48]:
np.subtract(a1,a2)

array([[[ 0.85613183, -0.14058243],
        [ 0.59264386, -0.47958011],
        [-0.97219332,  0.2475484 ]],

       [[ 0.25540224,  0.52634623],
        [-0.21352396,  0.67150136],
        [ 0.35175324,  0.01635457]]])

In [49]:
np.divide(a1,a2)

array([[[1.53506678e+01, 5.70010436e-01],
        [2.64210506e+00, 3.52761309e-01],
        [1.12188272e-02, 2.52350566e+00]],

       [[1.45606652e+00, 2.24305037e+00],
        [7.34891427e-01, 3.88615115e+00],
        [1.91909646e+00, 1.01820375e+00]]])

### statistic functions

In [ ]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.maz(a2)

## Appending and inserting

In [54]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

## append the ones into the zeoes

In [58]:
appd = np.append(zeroes, new_array, axis=0) # axis = 0 means add it as rows. axis =1 means add it as columns
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

## Insert 

In [59]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [60]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [61]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0) # means insert the ones into the zeroes and place it as the 2nd row
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## Delete

In [63]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.35741112, 0.29642254, 0.96907154],
        [0.41340355, 0.64353719, 0.93560123]],

       [[0.37508815, 0.07028627, 0.41020245],
        [0.00736519, 0.18672562, 0.31895036]],

       [[0.51386229, 0.96888525, 0.92361583],
        [0.14319047, 0.02514824, 0.66015801]]])

In [65]:
arr5=np.delete(arr4,0, axis=1)

In [66]:
arr5

array([[[0.41340355, 0.64353719, 0.93560123]],

       [[0.00736519, 0.18672562, 0.31895036]],

       [[0.14319047, 0.02514824, 0.66015801]]])

## save the array on fiel

In [67]:
np.save("saved_array", arr5)

## load the saved array

In [68]:
np.load("saved_array.npy")

array([[[0.41340355, 0.64353719, 0.93560123]],

       [[0.00736519, 0.18672562, 0.31895036]],

       [[0.14319047, 0.02514824, 0.66015801]]])